// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/puppies/service.proto

package puppies

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Name struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Name) Reset()         { *m = Name{} }
func (m *Name) String() string { return proto.CompactTextString(m) }
func (*Name) ProtoMessage()    {}
func (*Name) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65dd5d1e529768, []int{0}
}

func (m *Name) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Name.Unmarshal(m, b)
}
func (m *Name) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Name.Marshal(b, m, deterministic)
}
func (m *Name) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Name.Merge(m, src)
}
func (m *Name) XXX_Size() int {
	return xxx_messageInfo_Name.Size(m)
}
func (m *Name) XXX_DiscardUnknown() {
	xxx_messageInfo_Name.DiscardUnknown(m)
}

var xxx_messageInfo_Name proto.InternalMessageInfo

func (m *Name) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Name) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Update struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  float64  `protobuf:"fixed64,3,opt,name=age,proto3" json:"age,omitempty"`
	Weight               float64  `protobuf:"fixed64,4,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Update) Reset()         { *m = Update{} }
func (m *Update) String() string { return proto.CompactTextString(m) }
func (*Update) ProtoMessage()    {}
func (*Update) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65dd5d1e529768, []int{1}
}

func (m *Update) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Update.Unmarshal(m, b)
}
func (m *Update) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Update.Marshal(b, m, deterministic)
}
func (m *Update) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Update.Merge(m, src)
}
func (m *Update) XXX_Size() int {
	return xxx_messageInfo_Update.Size(m)
}
func (m *Update) XXX_DiscardUnknown() {
	xxx_messageInfo_Update.DiscardUnknown(m)
}

var xxx_messageInfo_Update proto.InternalMessageInfo

func (m *Update) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Update) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Update) GetAge() float64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Update) GetWeight() float64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type Breed struct {
	Breed                string   `protobuf:"bytes,1,opt,name=breed,proto3" json:"breed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Breed) Reset()         { *m = Breed{} }
func (m *Breed) String() string { return proto.CompactTextString(m) }
func (*Breed) ProtoMessage()    {}
func (*Breed) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65dd5d1e529768, []int{2}
}

func (m *Breed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Breed.Unmarshal(m, b)
}
func (m *Breed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Breed.Marshal(b, m, deterministic)
}
func (m *Breed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Breed.Merge(m, src)
}
func (m *Breed) XXX_Size() int {
	return xxx_messageInfo_Breed.Size(m)
}
func (m *Breed) XXX_DiscardUnknown() {
	xxx_messageInfo_Breed.DiscardUnknown(m)
}

var xxx_messageInfo_Breed proto.InternalMessageInfo

func (m *Breed) GetBreed() string {
	if m != nil {
		return m.Breed
	}
	return ""
}

type PuppyList struct {
	Puppy                []*Puppy `protobuf:"bytes,1,rep,name=puppy,proto3" json:"puppy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PuppyList) Reset()         { *m = PuppyList{} }
func (m *PuppyList) String() string { return proto.CompactTextString(m) }
func (*PuppyList) ProtoMessage()    {}
func (*PuppyList) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65dd5d1e529768, []int{3}
}

func (m *PuppyList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PuppyList.Unmarshal(m, b)
}
func (m *PuppyList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PuppyList.Marshal(b, m, deterministic)
}
func (m *PuppyList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PuppyList.Merge(m, src)
}
func (m *PuppyList) XXX_Size() int {
	return xxx_messageInfo_PuppyList.Size(m)
}
func (m *PuppyList) XXX_DiscardUnknown() {
	xxx_messageInfo_PuppyList.DiscardUnknown(m)
}

var xxx_messageInfo_PuppyList proto.InternalMessageInfo

func (m *PuppyList) GetPuppy() []*Puppy {
	if m != nil {
		return m.Puppy
	}
	return nil
}

type Puppy struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  float64  `protobuf:"fixed64,3,opt,name=age,proto3" json:"age,omitempty"`
	Weight               float64  `protobuf:"fixed64,4,opt,name=weight,proto3" json:"weight,omitempty"`
	PrimaryColor         string   `protobuf:"bytes,5,opt,name=primaryColor,proto3" json:"primaryColor,omitempty"`
	SecondaryColor       string   `protobuf:"bytes,6,opt,name=secondaryColor,proto3" json:"secondaryColor,omitempty"`
	Owner                string   `protobuf:"bytes,7,opt,name=owner,proto3" json:"owner,omitempty"`
	Location             string   `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	Motto                string   `protobuf:"bytes,9,opt,name=motto,proto3" json:"motto,omitempty"`
	Breed                string   `protobuf:"bytes,10,opt,name=breed,proto3" json:"breed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Puppy) Reset()         { *m = Puppy{} }
func (m *Puppy) String() string { return proto.CompactTextString(m) }
func (*Puppy) ProtoMessage()    {}
func (*Puppy) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65dd5d1e529768, []int{4}
}

func (m *Puppy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Puppy.Unmarshal(m, b)
}
func (m *Puppy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Puppy.Marshal(b, m, deterministic)
}
func (m *Puppy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Puppy.Merge(m, src)
}
func (m *Puppy) XXX_Size() int {
	return xxx_messageInfo_Puppy.Size(m)
}
func (m *Puppy) XXX_DiscardUnknown() {
	xxx_messageInfo_Puppy.DiscardUnknown(m)
}

var xxx_messageInfo_Puppy proto.InternalMessageInfo

func (m *Puppy) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Puppy) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Puppy) GetAge() float64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Puppy) GetWeight() float64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Puppy) GetPrimaryColor() string {
	if m != nil {
		return m.PrimaryColor
	}
	return ""
}

func (m *Puppy) GetSecondaryColor() string {
	if m != nil {
		return m.SecondaryColor
	}
	return ""
}

func (m *Puppy) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Puppy) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Puppy) GetMotto() string {
	if m != nil {
		return m.Motto
	}
	return ""
}

func (m *Puppy) GetBreed() string {
	if m != nil {
		return m.Breed
	}
	return ""
}

func init() {
	proto.RegisterType((*Name)(nil), "com.ge.rpc.Name")
	proto.RegisterType((*Update)(nil), "com.ge.rpc.Update")
	proto.RegisterType((*Breed)(nil), "com.ge.rpc.Breed")
	proto.RegisterType((*PuppyList)(nil), "com.ge.rpc.PuppyList")
	proto.RegisterType((*Puppy)(nil), "com.ge.rpc.Puppy")
}

func init() { proto.RegisterFile("rpc/puppies/service.proto", fileDescriptor_4d65dd5d1e529768) }

var fileDescriptor_4d65dd5d1e529768 = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0x4d, 0x6b, 0xdb, 0x40,
	0x10, 0x45, 0xb6, 0x25, 0x5b, 0x53, 0xe3, 0xba, 0x43, 0x5b, 0xb6, 0x82, 0x82, 0xd1, 0xa1, 0x35,
	0x3d, 0xc8, 0xc5, 0x6d, 0x0e, 0x39, 0xc6, 0x09, 0xe4, 0x12, 0x82, 0x71, 0x48, 0x02, 0xb9, 0xc9,
	0xd2, 0xa0, 0x2c, 0x58, 0xda, 0x65, 0xb5, 0x8e, 0xd1, 0xcf, 0xcd, 0x2f, 0x49, 0xd0, 0xae, 0xf1,
	0x47, 0x9c, 0x40, 0x0e, 0xb9, 0xcd, 0x7b, 0xf3, 0x66, 0x99, 0x79, 0xfb, 0xe0, 0x87, 0x92, 0xc9,
	0x48, 0x2e, 0xa5, 0xe4, 0x54, 0x8e, 0x4a, 0x52, 0x0f, 0x3c, 0xa1, 0x48, 0x2a, 0xa1, 0x05, 0x42,
	0x22, 0xf2, 0x28, 0xa3, 0x48, 0xc9, 0x24, 0xfc, 0x03, 0xad, 0xcb, 0x38, 0x27, 0xec, 0x41, 0x83,
	0xa7, 0xcc, 0x19, 0x38, 0x43, 0x7f, 0xd6, 0xe0, 0x29, 0x22, 0xb4, 0x8a, 0x38, 0x27, 0xd6, 0x30,
	0x8c, 0xa9, 0xc3, 0x1b, 0xf0, 0xae, 0x65, 0x1a, 0xeb, 0x77, 0xa9, 0xb1, 0x0f, 0xcd, 0x38, 0x23,
	0xd6, 0x1c, 0x38, 0x43, 0x67, 0x56, 0x97, 0xf8, 0x1d, 0xbc, 0x15, 0xf1, 0xec, 0x5e, 0xb3, 0x96,
	0x21, 0xd7, 0x28, 0xfc, 0x09, 0xee, 0x44, 0x11, 0xa5, 0xf8, 0x15, 0xdc, 0x79, 0x5d, 0xac, 0x5f,
	0xb6, 0x20, 0xfc, 0x0f, 0xfe, 0x74, 0x29, 0x65, 0x75, 0xc1, 0x4b, 0x8d, 0xbf, 0xc1, 0xad, 0x8f,
	0xaa, 0x98, 0x33, 0x68, 0x0e, 0x3f, 0x8d, 0xbf, 0x44, 0xdb, 0x5b, 0x22, 0xa3, 0x9a, 0xd9, 0x7e,
	0xf8, 0xe4, 0x80, 0x6b, 0x88, 0x8f, 0x5d, 0x16, 0x43, 0xe8, 0x4a, 0xc5, 0xf3, 0x58, 0x55, 0xa7,
	0x62, 0x21, 0x14, 0x73, 0xcd, 0x2b, 0x7b, 0x1c, 0xfe, 0x82, 0x5e, 0x49, 0x89, 0x28, 0xd2, 0x8d,
	0xca, 0x33, 0xaa, 0x17, 0x6c, 0x7d, 0xaf, 0x58, 0x15, 0xa4, 0x58, 0xdb, 0xde, 0x6b, 0x00, 0x06,
	0xd0, 0x59, 0x88, 0x24, 0xd6, 0x5c, 0x14, 0xac, 0x63, 0x1a, 0x1b, 0x5c, 0x4f, 0xe4, 0x42, 0x6b,
	0xc1, 0x7c, 0x3b, 0x61, 0xc0, 0xd6, 0x37, 0xd8, 0xf1, 0x6d, 0xfc, 0xe8, 0x40, 0x7b, 0x6a, 0x03,
	0x80, 0x7f, 0xc1, 0x3f, 0x27, 0x3d, 0xa9, 0xcc, 0x5f, 0xf7, 0x77, 0x4d, 0xab, 0x99, 0xe0, 0xd0,
	0x46, 0x1c, 0x43, 0xf7, 0x8c, 0x16, 0xa4, 0xe9, 0xcd, 0xa1, 0x03, 0x06, 0x8f, 0xe1, 0xb3, 0x0d,
	0xc8, 0x49, 0x46, 0xb7, 0xd6, 0x2e, 0xdc, 0x15, 0xd9, 0x66, 0xf0, 0x0a, 0x87, 0x47, 0xe0, 0x5f,
	0x25, 0x71, 0x61, 0x73, 0xb0, 0xb7, 0x8e, 0xa1, 0x82, 0x6f, 0x07, 0x1b, 0xd6, 0x71, 0x98, 0xf8,
	0x77, 0xed, 0x75, 0xc6, 0xe7, 0x9e, 0x09, 0xf7, 0xbf, 0xe7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x43,
	0x32, 0x89, 0x09, 0xf9, 0x02, 0x00, 0x00,
}
