// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/puppies/service.proto

package puppies

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetByIdReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByIdReq) Reset()         { *m = GetByIdReq{} }
func (m *GetByIdReq) String() string { return proto.CompactTextString(m) }
func (*GetByIdReq) ProtoMessage()    {}
func (*GetByIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65dd5d1e529768, []int{0}
}

func (m *GetByIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByIdReq.Unmarshal(m, b)
}
func (m *GetByIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByIdReq.Marshal(b, m, deterministic)
}
func (m *GetByIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByIdReq.Merge(m, src)
}
func (m *GetByIdReq) XXX_Size() int {
	return xxx_messageInfo_GetByIdReq.Size(m)
}
func (m *GetByIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetByIdReq proto.InternalMessageInfo

func (m *GetByIdReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetByIdReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Puppy struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  float64  `protobuf:"fixed64,3,opt,name=age,proto3" json:"age,omitempty"`
	Weight               float64  `protobuf:"fixed64,4,opt,name=weight,proto3" json:"weight,omitempty"`
	PrimaryColor         string   `protobuf:"bytes,5,opt,name=primaryColor,proto3" json:"primaryColor,omitempty"`
	SecondaryColor       string   `protobuf:"bytes,6,opt,name=secondaryColor,proto3" json:"secondaryColor,omitempty"`
	Owner                string   `protobuf:"bytes,7,opt,name=owner,proto3" json:"owner,omitempty"`
	Location             string   `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	Motto                string   `protobuf:"bytes,9,opt,name=motto,proto3" json:"motto,omitempty"`
	Breed                string   `protobuf:"bytes,10,opt,name=breed,proto3" json:"breed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Puppy) Reset()         { *m = Puppy{} }
func (m *Puppy) String() string { return proto.CompactTextString(m) }
func (*Puppy) ProtoMessage()    {}
func (*Puppy) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d65dd5d1e529768, []int{1}
}

func (m *Puppy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Puppy.Unmarshal(m, b)
}
func (m *Puppy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Puppy.Marshal(b, m, deterministic)
}
func (m *Puppy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Puppy.Merge(m, src)
}
func (m *Puppy) XXX_Size() int {
	return xxx_messageInfo_Puppy.Size(m)
}
func (m *Puppy) XXX_DiscardUnknown() {
	xxx_messageInfo_Puppy.DiscardUnknown(m)
}

var xxx_messageInfo_Puppy proto.InternalMessageInfo

func (m *Puppy) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Puppy) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Puppy) GetAge() float64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Puppy) GetWeight() float64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Puppy) GetPrimaryColor() string {
	if m != nil {
		return m.PrimaryColor
	}
	return ""
}

func (m *Puppy) GetSecondaryColor() string {
	if m != nil {
		return m.SecondaryColor
	}
	return ""
}

func (m *Puppy) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Puppy) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Puppy) GetMotto() string {
	if m != nil {
		return m.Motto
	}
	return ""
}

func (m *Puppy) GetBreed() string {
	if m != nil {
		return m.Breed
	}
	return ""
}

func init() {
	proto.RegisterType((*GetByIdReq)(nil), "com.ge.rpc.GetByIdReq")
	proto.RegisterType((*Puppy)(nil), "com.ge.rpc.Puppy")
}

func init() { proto.RegisterFile("rpc/puppies/service.proto", fileDescriptor_4d65dd5d1e529768) }

var fileDescriptor_4d65dd5d1e529768 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcf, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x49, 0x7f, 0xa5, 0x19, 0xa4, 0xe8, 0x20, 0x65, 0xed, 0xa9, 0xe4, 0x20, 0x3d, 0xa5,
	0xa2, 0xde, 0x85, 0x7a, 0x10, 0x6f, 0x25, 0x47, 0x6f, 0xe9, 0x66, 0x88, 0x0b, 0x4d, 0x66, 0xdd,
	0x6c, 0x2d, 0xf9, 0xeb, 0x95, 0x4c, 0x42, 0xab, 0x9e, 0xbc, 0xed, 0xfb, 0xe6, 0xcd, 0x1e, 0xbe,
	0x81, 0x1b, 0x67, 0xf5, 0xda, 0x1e, 0xac, 0x35, 0x54, 0xaf, 0x6b, 0x72, 0x9f, 0x46, 0x53, 0x62,
	0x1d, 0x7b, 0x46, 0xd0, 0x5c, 0x26, 0x05, 0x25, 0xce, 0xea, 0xf8, 0x0e, 0xe0, 0x85, 0xfc, 0xa6,
	0x79, 0xcd, 0x53, 0xfa, 0xc0, 0x19, 0x0c, 0x4c, 0xae, 0x82, 0x65, 0xb0, 0x8a, 0xd2, 0x81, 0xc9,
	0x11, 0x61, 0x54, 0x65, 0x25, 0xa9, 0x81, 0x10, 0x79, 0xc7, 0x5f, 0x01, 0x8c, 0xb7, 0x07, 0x6b,
	0x9b, 0xff, 0xb4, 0xf1, 0x12, 0x86, 0x59, 0x41, 0x6a, 0xb8, 0x0c, 0x56, 0x41, 0xda, 0x3e, 0x71,
	0x0e, 0x93, 0x23, 0x99, 0xe2, 0xdd, 0xab, 0x91, 0xc0, 0x3e, 0x61, 0x0c, 0x17, 0xd6, 0x99, 0x32,
	0x73, 0xcd, 0x33, 0xef, 0xd9, 0xa9, 0xb1, 0xfc, 0xf2, 0x8b, 0xe1, 0x2d, 0xcc, 0x6a, 0xd2, 0x5c,
	0xe5, 0xa7, 0xd6, 0x44, 0x5a, 0x7f, 0x28, 0x5e, 0xc3, 0x98, 0x8f, 0x15, 0x39, 0x15, 0xca, 0xb8,
	0x0b, 0xb8, 0x80, 0xe9, 0x9e, 0x75, 0xe6, 0x0d, 0x57, 0x6a, 0x2a, 0x83, 0x53, 0x6e, 0x37, 0x4a,
	0xf6, 0x9e, 0x55, 0xd4, 0x6d, 0x48, 0x68, 0xe9, 0xce, 0x11, 0xe5, 0x0a, 0x3a, 0x2a, 0xe1, 0xfe,
	0x09, 0xc2, 0x6d, 0x27, 0x16, 0x1f, 0x21, 0xec, 0xf5, 0xe1, 0x3c, 0x39, 0x6b, 0x4d, 0xce, 0x4e,
	0x17, 0x57, 0x3f, 0xb9, 0x88, 0xdb, 0x44, 0x6f, 0x61, 0x7f, 0x99, 0xdd, 0x44, 0x4e, 0xf2, 0xf0,
	0x1d, 0x00, 0x00, 0xff, 0xff, 0x87, 0x6e, 0x61, 0x37, 0xaf, 0x01, 0x00, 0x00,
}
